### ISSUE TITLE
小程序代码下载后在微信开发者工具里打开就报错

### ISSUE THREAD

**Issue by pengrui2015** [wildfirechat/wx-chat#1]
![image](https://user-images.githubusercontent.com/12092790/68730830-0a917a80-0609-11ea-81d8-eb13ccb837a9.png)

**Comment by jessecoding** [comment]
我也遇到一样问题，有人跟进一下吗？

**Comment by imndx** [comment]
抱歉，我刚看到这问题。
可能是忘了将依赖加入到package.json里面去了，请执行下面命名，然后测试
```npm install base64-arraybuffer --save ```

**Comment by imndx** [comment]
已修复，请参考readme

**Comment by pengrui2015** [comment]
好的，谢谢
