### ISSUE TITLE
使用社区版Server本地部署，小程序连接失败

### ISSUE THREAD

**Issue by Hipple** [wildfirechat/wx-chat#2]
小程序连接代码：
wfc.connect('我自己的appId', '我自己的appKey', 'http://192.168.1.163', '80', userId, clientId, token);

错误如下：
![image](https://user-images.githubusercontent.com/13818792/71173695-584f7180-229e-11ea-84a5-456cdaa0caf7.png)
运行demo时连接成功后会打印一个key，我这里却只打印了一个未识别的字符。

检查了参数是没问题的，clientId使用wfc.getClientId()时会报uuid未找到的错误，我自己生成了唯一ID当做clientId，token是应用服务器返回的

debug看了下im_server，aes解密uid时候得到的byte[]为空，我没找到这里为空的原因

想请问下是哪里的问题？

**Comment by imndx** [comment]
你好，小程序SDK是需要付费的，不能直接修改连接地址。

请参考[野火IM收费点说明](http://docs.wildfirechat.cn/#%E8%B4%B9%E7%94%A8)
