### ISSUE TITLE
自定义消息，服务端更新消息不能保存

### ISSUE THREAD

**Issue by zhangkinge** [wildfirechat/wx-chat#5]
服务端更新消息能体现，但是再发一条消息或者退出聊天界面再次进入又变成原本的内容。求帮助 自定消息代码如下： 收到服务端消息的时候 decode中binaryContent数据是想要的。
自定义消息如下：

    export default class BuyVehicleRequestMessageContent extends MessageContent {
    content;
    orderInfo;

    constructor(content, extra, mentionedType = 0, mentionedTargets = []) {
        super(MessageContentType.MESSAGE_CONTENT_TYPE_BUYVEHICLE_REQUEST, mentionedType, mentionedTargets);
        this.content = content;
        this.orderInfo = extra
    }

    digest() {
        return "[定车申请]";
    }

    encode() {
        let payload = super.encode();
        payload.searchableContent = this.content;
        payload.binaryContent = wfc.utf8_to_b64(JSON.stringify(this.orderInfo));
        return payload;
    }

    decode(payload) {
        super.decode(payload);
        console.log("开始:decode")
        this.content = payload.content;
        this.searchableContent = payload.searchableContent
        if (payload.binaryContent && payload.binaryContent.length > 0) {
            // JSON.parse 和 JSON.stringify 不能处理java long
            payload.extra =JSON.parse(wfc.b64_to_utf8(payload.binaryContent))
            console.log("orderState:"+payload.extra.orderState)
            this.binaryContent = payload.binaryContent
            this.extra = payload.extra
        }
    }
  }

服务端更新消息内容如下：

           MessagePayload payload = new MessagePayload();
            payload.setType(msgType);
            payload.setSearchableContent(text);
            payload.setBase64edData(Base64Utils.encodeToString(data.toString().getBytes()));
            payload.setPersistFlag(ProtoConstants.PersistFlag.Persist_And_Count);

            IMResult<Void> imResult = MessageAdmin.updateMessageContent("admin", messageId, payload, true);

**Comment by imndx** [comment]
这问题是在wx-chat，还是 uni-chat 出现的？

**Comment by imndx** [comment]
你好，这个问题在 `2023-05-06`之后的版本上，应当修复了的，请确认

**Comment by zhangkinge** [comment]
> 这问题是在wx-chat，还是 uni-chat 出现的？

你好，是wx-chat。  
IM服务端专业版，用的版本是 "buildTime":"20220210110435" ，会不会有影响。

**Comment by imndx** [comment]
> > 这问题是在wx-chat，还是 uni-chat 出现的？
> 
> 你好，是wx-chat。 IM服务端专业版，用的版本是 "buildTime":"20220210110435" ，会不会有影响。

你好，小程序 SDK，可能也是这个时候的，你可以通过在`proto.min.js`文件里面搜索`WFCWebSDKVersion`这个字符串确认

**Comment by zhangkinge** [comment]
> > > 这问题是在wx-chat，还是 uni-chat 出现的？
> > 
> > 
> > 你好，是wx-chat。 IM服务端专业版，用的版本是 "buildTime":"20220210110435" ，会不会有影响。
> 
> 你好，小程序 SDK，可能也是这个时候的，你可以通过在`proto.min.js`文件里面搜索`WFCWebSDKVersion`这个字符串确认

刚刚已经下载了最新版本并把wfc文件夹替换到项目中。我的`proto.min.js`是由对接人员提供的，version="WFCWebSDKVersion-2024-09-30-90-066b64b"

**Comment by imndx** [comment]
`WFCWebSDKVersion-2024-09-30-90-066b64b`这个版本应当是没问题的，你测试下看看

**Comment by zhangkinge** [comment]
> `WFCWebSDKVersion-2024-09-30-90-066b64b`这个版本应当是没问题的，你测试下看看

不行哦。

**Comment by imndx** [comment]
你好，我们测试了下，能正常被远程更新，切换会话，发送新消息等，也不会恢复到原始消息。

请你微信添加下：wfchat，他协助你看下

**Comment by imndx** [comment]
> if (payload.binaryContent && payload.binaryContent.length > 0) {
>         // JSON.parse 和 JSON.stringify 不能处理java long
>         payload.extra =JSON.parse(wfc.b64_to_utf8(payload.binaryContent))
>         console.log("orderState:"+payload.extra.orderState)
>         this.binaryContent = payload.binaryContent
>         this.extra = payload.extra
>     }

你的`encode`方法和`decode` 方法 没有对应起来呀

**Comment by zhangkinge** [comment]
非常感谢野火方的耐心解答，问题已解决，总结如下。
1.不能使用extra 保存自定义消息的信息
2.encode(){}、decode(payload) {}两个方法要对应起来，即：
   payload.binaryContent = wfc.utf8_to_b64(JSON.stringify(this.orderInfo)); 
和
 this.orderInfo =JSON.parse(wfc.b64_to_utf8(payload.binaryContent))。
