### ISSUE TITLE
发现的几个小问题

### ISSUE THREAD

**Issue by zhangkinge** [wildfirechat/wx-chat#6]
1.语音信息只能播放一次
voice-manager.js->_playVoice() 中 调用await this._myPlayVoice({ filePath });之后要设置  data.chatItems[dataset.index].isPlaying= false
2..语音信息播放过程中点同一语音信息停止播放后，再次点语音信息不能播放
voice-manager.js->_stopAllVoicePlay() 中 发现语音信息 item.type 为null,    改为  if ('voice' === item.type || item.messageContent instanceof SoundMessageContent)
3.接收到消息即使时间很接近每条都会显示时间
chat.js -> messagesToUiMessages()中的 lastTimestamp 应设置为全局变量。
供参考

**Comment by imndx** [comment]
谢谢反馈 :smile:
